#!/bin/bash
#
#                 BIOBASH v0.1
# Bioinformatics and Systems Biology Laboratory
# Institute for Genetics - National University of Colombia
# https://gibbslab.github.io/
#
# Released on: 2020-10-28
#
#!/bin/bash


if [ -z "$1" ] ; then
    echo "
		
		bb_count_seqs: Counts the number of fasta or fastq sequences in a file.
		Usage: bb_count_seqs [INPUT FILE]
                Expects the following file extensions: .fasta, .fastq, .fa or .fq

    "	
fi


if [ "${1##*.}" = "fasta" ] || [ "${1##*.}" = "fa" ]; then

	   grep -c '>' $1
          exit 0
fi

if [ "${1##*.}" = "fastq" ] || [ "${1##*.}" = "fq" ]; then

	   x=$(wc -l $1 | awk '{ print $1 }') 
           var3=$(bc <<< "$x / 4")
           echo $var3
           exit 0
else
		echo "ERROR: Unable to process input file."
		echo "It seems your file is not fasta (.fasta, .fa) or fastq (.fastq, .fq) file."
fi

	

