#!/bin/bash
#
#                 BIOBASH v0.1
# Bioinformatics and Systems Biology Laboratory
# Institute for Genetics - National University of Colombia
# https://gibbslab.github.io/
#
# Released on: 2020-10-20
#
#!/bin/bash
        #This script is  called by bb_get_GC_content!!!!!!
	if [ -z "$1" ] ; then
		echo "
		bb_count_residues: counts the number of residues in a file, without taking into account
		fasta headers.
		Usage: bb_count_residues [INPUT FILE]
		"
	fi
	# first colum is obtained from result, otherwise an space appears at left.
	cat $1 | sed -e '/^>/d' | tr -d '\n' | wc -m | awk '{print $1}'
	
