#!/bin/bash
#
#                 BIOBASH v0.1
# Bioinformatics and Systems Biology Laboratory
# Institute for Genetics - National University of Colombia
# https://gibbslab.github.io/
#
# Released on: 2020-10-28
#
#!/bin/bash
#Usually this function would remove all windows characters from end of line...
#not sure about it, maybe get it out or create a more robust one.
	
if [ -z "$1" ] ; then
		echo "
		bb_dos2unix: removes windows characters from end of line.
		Usage: bb_dos2unix [INPUT FILE]
		"
fi
		cat $1 | col -b
