#!/bin/bash
#
#                 BIOBASH v0.1
# Bioinformatics and Systems Biology Laboratory
# Institute for Genetics - National University of Colombia
# https://gibbslab.github.io/
#
# Released on: 2020-10-28
#
	if [ -z "$1" ] ; then
		echo "
		bb_get_fasta_headers: ouputs a list of all fasta headers in a file.
		Usage: bb_get_fasta_headers [INPUT FILE]
		"
	fi
	grep '>' $1  | sed -e 's/>//'
	
