#!/bin/bash
#
#                 BIOBASH v0.1
# Bioinformatics and Systems Biology Laboratory
# Institute for Genetics - National University of Colombia
# https://gibbslab.github.io/
#
# Released on: 2020-10-18
#
	
	if [ -z "$1" ] ; then
		echo "
		bb_get_GC_content: gets the GC percentage of a file.
		Usage: bb_get_GC_content [INPT FILE]
		"
	fi
	isMultiple=$(grep -c '>' $1)
	if [ "$isMultiple" -gt "1" ] ; then
		echo "This is a multiple fasta file. You need a single fasta file."
		exit
	fi
	numResidues=$(bb_count_residues $1)
	g=$(cat $1 | sed -e '/^>/d' | tr -d '\n' | grep -oi 'G' | wc -l | awk '{print $1}')
	c=$(cat $1 | sed -e '/^>/d' | tr -d '\n' | grep -oi 'C' | wc -l | awk '{print $1}')
	perc=$(echo "(($g+$c)*100)/$numResidues" | bc)
	echo "$perc"
	#brute force algorithm above, can be improved using AWK's split function:
	#http://stackoverflow.com/questions/8009664/split-string-to-array-using-awk
	#or with the following code corrected (take out end of line chars)
	#noHead=$(bb_remove_fasta_header $1)
	#nonAT=$(echo "$noHead" | tr -d 'AaTt\n')
	#echo "$nonAT"
	#echo "$nonAT" | wc -m
		
	
