#!/bin/bash
#
#                 BIOBASH v0.1
# Bioinformatics and Systems Biology Laboratory
# Institute for Genetics - National University of Colombia
# https://gibbslab.github.io/
#
# Released on: 2020-10-17
#
	if [ -z "$1" ] ; then
		echo "
		bb_get_nr_list: Given a one colum file with a  list of items, this function outputs a
		new version of the list where redundant items are removed from the list. This means that
		if the file has the items: A, B, A, B, D, C and D. The output will be: A, B, C and D (in
		one column format).
		Usage: bb_get_nr_list [INPUT FILE]
		"
	fi
	
	FILEA=$(bb_create_tmp_file)
	FILEB=$(bb_create_tmp_file)
	FILEC=$(bb_create_tmp_file)
	
	cat $1 | sort  > $FILEA
	uniq -u $FILEA > $FILEB
	uniq -d $FILEA > $FILEC
	cat $FILEB $FILEC | sort
	
