#!/bin/bash
#
#                 BIOBASH v0.1
# Bioinformatics and Systems Biology Laboratory
# Institute for Genetics - National University of Colombia
# https://gibbslab.github.io/
#
# Released on: 2020-10-28
#
	if [ -z "$1" ] ; then
		echo "
		bb_remove_fasta_header: removes all fasta headers from a multipe o single fasta file. Useful to concatenate a multiple fasta file.
		If you want to create a list of all fasta headers in a file use: bb_get_fasta_headers.
		Usage: bb_remove_fasta_headers [INPUT FILE]
		"
	fi
		sed '/>/d' $1

