#!/bin/bash
#
#                 BIOBASH v0.1
# Bioinformatics and Systems Biology Laboratory
# Institute for Genetics - National University of Colombia
# https://gibbslab.github.io/
#
# Released on: 2020-10-28
#
	if [ -z "$1" ] ; then
		 echo "
		 bb_remove_empty_lines: removes empty lines from a file.
		 Usage: bb_remove_empty_lines [INPUT FILE]
		 "
	fi
		sed '/^$/d' $1

