#!/bin/bash
#This script was adapted from:
# https://bioinformaticsworkbook.org/dataWrangling/fastaq-manipulations/converting-fastq-format-to-fasta.html#gsc.tab=0


if [ -z "$1" ] ; then
    echo "
        bb_fastq2fasta: Converts fastq into fasta.
        Usage: bb_reformat_fastq2fasta [INPUT FILE]
    "
fi

#Read every 4 lines
sed -n '1~4s/^@/>/p;2~4p' $1
