#!/bin/bash
# Adapted from: https://gist.github.com/danielecook/394958db37c4d01f0ef3

if [ -z  "$1" ]; then
    echo "
        bb_get_seqs_length: Displays sequences length from a single/multiple fasta file
    
    Usage: bb_get_seqs_length [FASTA FILE]
    "
    exit
fi

awk '$1 ~ ">" {print c; c=0;printf substr($1,2,100) "\t"; } $1 !~ ">" {c+=length($1);} END { print c; }' $1

