#!/bin/bash

if [ -z "$1" ] ; then
    echo "
        Missing argument.
        bb_rename_seqs: Renames the header of a FASTA file.
        Usage: bb_rename_seqs [INPUT FILE]
    "
    exit 0
fi


awk '
BEGIN{FS="|"}
{
    #substr(s, a, b) : it returns b number of chars from string s, starting at position a. 
    #The parameter b is optional, in which case it means up to the end of the string.
    #String es entonces el archivo de entrada.
    
    
    if (substr($1,1,1) == ">"){
    numseq++;
        if(NR>1){
            printf "\n>X%s\n", numseq;
    }else{
        printf ">X%s\n", numseq;
    }

    }else{
        printf "%s", $1
    }
}

END{printf "\n"}' "$@"
