#!/bin/bash
#
# This script puts together all the files to create the "Official" BB release
# It should be a single file holding all functions.
#

VERSION="0.1"
DATE=`date +%Y-%m-%d`
RELEASEFILE="biobash_v."$VERSION".sh"

#concatenate  all files

echo -en "#!/bin/bash
# BIOBASH v$VERSION
#
# Released on: $DATE
" > version.inc

#Put header to all scripts
for i in $(ls *bb_*);do cat version.inc  $i > RL_$i;done

#cleaning up!
rm version.inc 

#perform tests

#move release
rm ../release/*
mv *RL_* ../release/
rename 's/RL_//' ../release/*
cp installbiobash ../release/
chmod +x ../release/*
cp INSTALL LICENSE README.md ../release/
