#!/bin/bash
#
# Puts together all the files to create the "Official" BB release
#

VERSION="0.1"
DATE=`date +%Y-%m-%d`
RELEASEFILE="biobash_v."$VERSION".sh"

#concatenate  all files

echo -en "#!/bin/bash
#
#                 BIOBASH v$VERSION
# Bioinformatics and Systems Biology Laboratory
# Institute for Genetics - National University of Colombia
# https://gibbslab.github.io/
#
# Released on: $DATE
#
" > version.inc

#Put header to all scripts and rename new files, so
# we move Release Files, not source files.
for i in $(ls *bb_*);do cat version.inc  $i > RL_$i;done

#cleaning up!
rm version.inc 

#perform tests

#Delete all previous release files.
rm ../release/*bb_*

# Necessary so we do not erase source files
mv *RL_* ../release/
#Rename again files so they do not contain the RL_
rename 's/RL_//' ../release/*
chmod +x ../release/*bb_*
