#
#  Andres Pinzon Ph. D. [ampinzonv@unal.edu.co] 
#  Bioinformatics and Systems Biology Group 
#  https://gibbslab.github.io/
#  Institute for Genetics - National University of Colombia
#  Tel: +57 1 3165000 Ext. 11618
#
# This is a set of functions written in BASH intended to perform common
# analysis in boinformatics. Most of them can also be performed n any 
# high level language such as Python or perl, but the idea behind BB
# is that all this routines can be integrated into the regular bash
# environment and be used as a regular bash function without the need
# of any dependencies beyond regular bash libraries.
# 
# This set of functions are divided into the following categories:
# 
# LIST MANIPULATION
# General manipulation of lists, such as gettin non redundant lists
# counting number of items etc.
#
# FASTA and FASTQ MANIPULATION
# Routines for G/C counting content, headers removal, pattern finding, 
# amongst others.
#
# 
# By default, each routine outputs to STDOUT.
#

